
version: "3"

services:
  myapp:
    build: .
    ports:
     - "3000:80"
    environment:
      - PORT=3001


    depends_on:
     - mymongo
  
  mymongo: 
    image: "mongo:3.2"
    container_name: "my_mongo_container"
    ports: 
      - "27017:27017"
